// AI transport is unit-tested with mocked Responses; browser fixtures start from a recorded recognition result.
// This suite does not claim to measure real-model recognition accuracy and never calls a paid API.
const {suite}=require('./lib/harness.cjs');
const fs=require('fs'),path=require('path');
const t=suite('floorplan');
const quote=s=>"'"+String(s).replaceAll("'","''")+"'";
const scalar=q=>Number(t.sql(q));
const plan={isFloorplan:true,supported:true,outline:[[.1,.1],[.9,.1],[.9,.9],[.1,.9]],walls:[{a:[.5,.1],b:[.5,.9]}],openings:[{kind:'door',a:[.5,.5],b:[.5,.6]},{kind:'window',a:[.18,.1],b:[.38,.1]}],labels:[{point:[.3,.5],name:'거실',kind:'living'},{point:[.7,.5],name:'침실',kind:'bed'}],widthMm:null,dimensionEvidence:'',warnings:['테스트로 저장한 인식 결과 · 실제 AI 인식 정확도 검증 아님']};
const house=pid=>JSON.parse(t.sql(`select house from versions where id=(select current_version_id from projects where id=${pid})`));
t.run(async()=>{
  const c=await t.page();await t.login(c,'customer@demo.kr');
  const customer=scalar("select id from users where email='customer@demo.kr'");
  const other=scalar("select id from users where email='vendor1@demo.kr'");
  const admin=await t.page();await t.login(admin,'admin@demo.kr');
  t.group('도면 업로드 및 키 없음');
  await c.goto(t.B+'/spaces/recognize');
  t.check('실제 API 키 없음을 표시하고 인식 버튼 비활성',await c.locator('[data-testid=ai-unavailable]').count()===1 && await c.locator('[data-testid=ai-analyze]').isDisabled());
  await c.setInputFiles('[data-testid=recognize-file]',t.fixture('trace-R.png'));
  await c.waitForSelector('[data-testid=recognition-image]');
  t.check('도면 이미지 미리보기 로드',await c.locator('[data-testid=recognition-image]').evaluate(x=>x.naturalWidth>0));
  t.check('키 없는 업로드가 작업·프로젝트를 만들지 않음',scalar('select count(*) from floorplan_jobs')===0);
  await c.setInputFiles('[data-testid=recognize-file]',t.fixture('trace-L.pdf'));
  await c.waitForFunction(()=>document.querySelector('[data-testid=recognition-image]')?.naturalWidth>0);
  t.check('PDF를 도면 이미지로 변환하여 로드',await c.locator('[data-testid=recognition-image]').count()===1);
  await t.shot(c,'upload-pdf');
  const bytes=fs.readFileSync(t.fixture('trace-R.png')),iw=bytes.readUInt32BE(16),ih=bytes.readUInt32BE(20);
  const fileName='floorplan-fixture.png';fs.copyFileSync(t.fixture('trace-R.png'),path.join(path.dirname(t.DB),'uploads',fileName));
  const fid=scalar(`insert into files(owner_id,kind,original_name,stored_name,mime,size,category) values(${customer},'photo','floorplan.png','${fileName}','image/png',${bytes.length},'ai-floorplan');select last_insert_rowid();`);
  const makeJob=(owner=customer,data=plan,status='ready')=>scalar(`insert into floorplan_jobs(owner_id,file_id,status,result,iw,ih) values(${owner},${fid},'${status}',${quote(JSON.stringify(data))},${iw},${ih});select last_insert_rowid();`);
  const job=makeJob(),foreign=makeJob(other);
  t.group('기록된 인식 결과 확인·3D·저장');
  await c.goto(t.B+`/spaces/recognize?job=${job}`);
  t.check('원본 위에 벽·문·창 인식 결과 표시',await c.locator('[data-testid=recognition-overlay] line').count()===3);
  t.check('실제 치수 없이 저장 비활성',await c.locator('[data-testid=ai-import]').isDisabled());
  await c.fill('[data-testid=ai-width]','10000');
  await c.waitForSelector('[data-testid=house-view]');
  t.check('도면 종횡비를 유지한 치수 미리보기', (await c.locator('[data-testid=house-summary]').textContent()).includes('10,000'));
  t.check('AI 출처와 확인 전 안내',await c.locator('[data-testid=house-provenance]').textContent().then(s=>s.includes('AI 도면 인식')&&s.includes('업체 확인 전')));
  await c.click('[data-testid=house-tab-3d]');await c.waitForSelector('[data-testid=house-3d] canvas');
  t.check('인식 결과가 실제 3D 장면으로 연결',await c.locator('[data-testid=house-3d] canvas').count()===1);
  await t.shot(c,'recognition-3d');
  await c.check('[data-testid=ai-confirm]');
  const nProjects=scalar('select count(*) from projects');
  await c.click('[data-testid=ai-import]');await c.waitForURL(/projects\/\d+\/house\/edit/);
  const pid=Number(c.url().match(/projects\/(\d+)/)[1]),h=house(pid);
  t.check('공사 요청 없이 내 공간 생성',scalar(`select requested_version_id is null from projects where id=${pid}`)===1 && scalar('select count(*) from projects')===nProjects+1);
  t.check('내부 벽·문·창·라벨이 정확히 저장',h.walls.length===1 && h.openings.length===2 && h.labels.length===2 && h.width===10);
  t.check('원본 도면은 비공개 밑그림으로 연결',h.underlay.fileId===fid && t.sql(`select category from files where id=${fid}`)==='underlay');
  t.check('저장한 인식 작업은 한 번만 사용',t.sql(`select status||':'||accepted_project_id from floorplan_jobs where id=${job}`)===`used:${pid}`);
  await c.goto(t.B+`/spaces/recognize?job=${job}`);await c.waitForURL(/house\/edit/);
  t.check('같은 결과 다시 열어도 프로젝트를 중복 생성하지 않음',scalar('select count(*) from projects')===nProjects+1);
  t.check('편집기에 AI 출처·임시값 안내 유지',await c.locator('[data-testid=editor-provenance]').count()===1);
  await c.click('[data-testid=mode-furniture]');await c.click('[data-testid=add-h-bed-single]');await c.click('[data-testid=editor-save]');
  await t.until(()=>house(pid).items.length===1);
  t.check('기존 편집기에서 가구 추가·저장',house(pid).items.length===1 && house(pid).provenance.kind==='ai');
  await c.reload();t.check('다시 열어도 배치·AI 출처 보존',house(pid).items.length===1 && await c.locator('[data-testid=editor-provenance]').count()===1);
  t.group('권한·치수·손상 결과');
  const outsider=await t.page();
  t.check('비로그인 원본 도면 열람 차단',(await outsider.request.get(t.B+`/files/${fid}`)).status()===404);
  const badres=await c.goto(t.B+`/spaces/recognize?job=${foreign}`);t.check('다른 계정 인식 결과 열람 차단',badres.status()===404);
  const next=makeJob();await c.goto(t.B+`/spaces/recognize?job=${next}`);await c.fill('[data-testid=ai-width]','10000');await c.check('[data-testid=ai-confirm]');
  await c.locator('input[name=job]').evaluate((el,id)=>{el.value=String(id);},foreign);
  const beforeTamper=scalar('select count(*) from projects');await c.click('[data-testid=ai-import]');await c.waitForSelector('p[role=alert]');
  t.check('변조한 다른 계정 작업 저장 차단',scalar('select count(*) from projects')===beforeTamper && (await c.locator('p[role=alert]').textContent()).includes('내 도면'));
  const expired=makeJob();t.sql(`update floorplan_jobs set expires_at='2000-01-01' where id=${expired}`);await c.goto(t.B+`/spaces/recognize?job=${expired}`);
  t.check('만료된 인식 결과를 확인 화면에 내놓지 않음',await c.locator('[data-testid=recognition-review]').count()===0);
  const wrong=structuredClone(plan);wrong.walls[0].b=[.6,.9];const invalid=makeJob(customer,wrong);
  await c.goto(t.B+`/spaces/recognize?job=${invalid}`);await c.fill('[data-testid=ai-width]','10000');
  t.check('기운 벽을 수정 없이 저장하지 못함',await c.locator('[data-testid=ai-import]').isDisabled() && (await c.locator('main').textContent()).includes('직각'));
  const guard=makeJob();await c.goto(t.B+`/spaces/recognize?job=${guard}`);await c.fill('[data-testid=ai-width]','10000');
  await c.locator('[data-testid=ai-import]').evaluate(el=>{el.form.noValidate=true;});
  const guardCount=scalar('select count(*) from projects');await c.click('[data-testid=ai-import]');await c.waitForSelector('p[role=alert]');
  t.check('고객 확인을 생략한 직접 제출을 서버에서 거부',scalar('select count(*) from projects')===guardCount && (await c.locator('p[role=alert]').textContent()).includes('확인'));
  await c.check('[data-testid=ai-confirm]');await c.locator('input[name=heightMm]').evaluate(el=>{el.value='not-a-number';});await c.click('[data-testid=ai-import]');
  await t.until(async()=> (await c.locator('p[role=alert]').textContent()).includes('천장'));
  t.check('변조한 천장 치수를 기본 높이로 바꾸지 않고 거부',scalar('select count(*) from projects')===guardCount && (await c.locator('p[role=alert]').textContent()).includes('천장'));
  await c.goto(t.B+`/spaces/recognize?job=${guard}`);await c.fill('[data-testid=ai-width]','10000');await c.check('[data-testid=ai-confirm]');await c.locator('input[name=widthMm]').evaluate(el=>{el.value='0';});await c.click('[data-testid=ai-import]');await c.waitForSelector('p[role=alert]');
  t.check('변조한 실제 가로 0mm는 서버에서 거부',scalar('select count(*) from projects')===guardCount);
  t.group('등록 도면 공개·선택·숨김');
  await admin.goto(t.B+'/admin/floorplans');
  await admin.selectOption('select[name=project]',String(pid));
  await admin.fill('input[name=complex]','검산 단지');await admin.fill('input[name=address]','검산로 10');await admin.fill('input[name=unit]','84A 확장형');await admin.fill('input[name=area]','84');await admin.fill('input[name=source]','테스트 도면 · 실제 판매 아님');await admin.check('input[name=rights]');
  await admin.locator('[data-testid=template-admin-form] button').click();await admin.waitForSelector('[role=status]');
  const tid=scalar('select max(id) from floorplan_templates'),th=JSON.parse(t.sql(`select house from floorplan_templates where id=${tid}`));
  t.check('운영자가 타입·출처를 확인하고 도면 등록',tid>0);
  t.check('공개 복사본에 원본 사진·가구·AI 정보 제외',!th.underlay && th.items.length===0 && !th.provenance);
  await c.goto(t.B+'/spaces/templates?q='+encodeURIComponent('검산로 10'));await c.waitForSelector(`[data-testid=template-${tid}]`);
  t.check('주소로 실제 등록 도면 검색',await c.locator(`[data-testid=template-${tid}]`).textContent().then(s=>s.includes('84A 확장형')));
  await c.click(`[data-testid=template-preview-${tid}]`);await c.waitForSelector('[data-testid=house-view]');
  t.check('타입 선택 전에 평면·3D 확인 가능',await c.locator('[data-testid=house-view]').count()===1);
  await c.check('[data-testid=template-confirm]');await c.click('[data-testid=template-import]');await c.waitForURL(/projects\/\d+\/house\/edit/);
  const copyId=Number(c.url().match(/projects\/(\d+)/)[1]);
  t.check('등록 도면은 내 공간 독립 복사본',copyId!==pid && house(copyId).provenance.kind==='template' && house(copyId).items.length===0 && !house(copyId).underlay);
  await c.click('[data-testid=mode-furniture]');await c.click('[data-testid=add-h-bed-single]');await c.click('[data-testid=editor-save]');await t.until(()=>house(copyId).items.length===1);
  t.check('등록 원본을 고치지 않고 내 공간만 편집',JSON.parse(t.sql(`select house from floorplan_templates where id=${tid}`)).items.length===0);
  await admin.reload();await admin.locator('li').filter({hasText:'검산 단지'}).getByRole('button',{name:'숨기기'}).click();
  await c.goto(t.B+'/spaces/templates?q='+encodeURIComponent('검산 단지'));t.check('숨긴 도면은 고객 검색에서 제외',await c.locator('[data-testid=templates-empty]').count()===1);
  await c.goto(t.B+`/projects/${copyId}/house`);t.check('등록 도면 숨겨도 고객 저장본 유지',await c.locator('[data-testid=house-view]').count()===1);
  t.group('기존 요청·업체 전달·모바일');
  await c.goto(t.B+`/projects/${pid}/request`);await c.fill('[data-testid=home-region]','서울 마포구');await c.click('[data-testid=home-send]');await c.waitForURL(new RegExp(`/projects/${pid}$`));
  const snap=JSON.parse(t.sql(`select snapshot from request_revisions where project_id=${pid} order by no desc limit 1`));
  t.check('업체에 보내는 요청에 선택한 평면·버전·AI 출처 보존',snap.house.provenance.kind==='ai' && snap.house.items.length===1);
  t.sql("update vendors set fields='office,home' where user_id=(select id from users where email='vendor1@demo.kr')");
  await admin.goto(t.B+`/admin/projects/${pid}`);
  const vendor=scalar("select id from vendors where user_id=(select id from users where email='vendor1@demo.kr')");
  await admin.check(`input[name=vendor][value="${vendor}"]`);await admin.locator('form:has(input[name=vendor]) button').click();
  const aid=scalar(`select id from assignments where project_id=${pid} and vendor_id=${vendor}`);
  const v=await t.page();await t.login(v,'vendor1@demo.kr');await v.goto(t.B+`/vendor/requests/${aid}`);
  t.check('배정된 업체가 동일한 평면·출처를 받음',await v.locator('[data-testid=house-view]').count()===1 && await v.locator('[data-testid=house-provenance]').textContent().then(s=>s.includes('AI 도면 인식')));
  const phone=await t.phone();await t.login(phone,'customer@demo.kr');
  await phone.goto(t.B+`/projects/${pid}/house/edit`);t.check('휴대폰 편집기 가로 넘침 없음',await t.noOverflow(phone));await t.shot(phone,'editor-mobile');
  const phoneJob=makeJob();await phone.goto(t.B+`/spaces/recognize?job=${phoneJob}`);await phone.fill('[data-testid=ai-width]','10000');
  t.check('휴대폰 원본·치수·3D 확인 화면 가로 넘침 없음',await t.noOverflow(phone));await t.shot(phone,'recognition-mobile');
  await phone.goto(t.B+'/spaces/templates');t.check('휴대폰 등록 도면 검색 가로 넘침 없음',await t.noOverflow(phone));
  await phone.goto(t.B+`/projects/${pid}/print`);t.check('인쇄·PDF에 AI 출처와 업체 확인 전 표시',await phone.locator('[data-testid=print-house]').textContent().then(s=>s.includes('AI 도면 인식')&&s.includes('업체 확인 전')));
  await admin.goto(t.B+'/admin/integrations');t.check('운영자 AI API 연결 상태 표시',(await admin.locator('[data-testid=integrations]').textContent()).includes('AI 도면 인식 (OpenAI)'));
  t.check('외래 키 무결성 유지',t.sql('pragma foreign_key_check;')==='');
});
