// 도면 따라 그리기와 설비·휴대폰 편집(예전 e2e9): ㄱ자 도면(PNG) 축척·모서리·벽 길이 맞춤·문·창·급배수·기둥 → 꺾인 공간 그대로 저장·편집·3D
// → 같은 도면 위에서 고치기 → 직사각형 도면(문 벽을 앞벽으로 돌림, 자동 배치) → PDF·DWG → 탕비 설비 자동 제안 위치/고객 확인 위치
// → 휴대폰 편집 화면 배치 → 꺾인 공간의 인쇄·요청 기록·업체 화면
// 도면: tests/e2e/fixtures/trace-L.png · trace-R.png · trace-L.pdf (만드는 법: fixtures/make-trace-fixtures.cjs)
const t = require("./lib/harness.cjs").suite("office-trace");
const { requestSpace } = require("./lib/office.cjs");
const { B, sql, check, group, login } = t;
const near = (a, b, e = 0.002) => Math.abs(a - b) <= e;

t.run(async () => {
  const ctx = (opts = {}) => t.page({ viewport: { width: 1440, height: 1300 }, ...opts });
  const placement = async (p) => JSON.parse(await p.getAttribute("main.editor", "data-placement"));
  const clickPx = async (p, u, v) => {
    const [x, y] = await p.$eval("[data-testid=trace-canvas]", (svg, [u, v]) => { const q = new DOMPoint(u, v).matrixTransform(svg.getScreenCTM()); return [q.x, q.y]; }, [u, v]);
    await p.mouse.click(x, y);
  };
  const roomOf = (pid) => JSON.parse(sql(`select room from versions where id=(select current_version_id from projects where id=${pid})`));
  const placementOf = (pid) => JSON.parse(sql(`select placement from versions where id=(select current_version_id from projects where id=${pid})`));

  const c = await ctx();
  await login(c, "customer@demo.kr");

  group("1. 도면 따라 그리기: ㄱ자 도면(PNG) → 꺾인 공간 그대로");
  await c.goto(B + "/spaces/new");
  await c.click("label.intake-option:has(input[value=drawing])");
  check("마법사: 도면 있음 → 따라 그리기 입구", await c.locator("[data-testid=go-trace]").isVisible());
  await c.click("[data-testid=go-trace]"); await c.waitForURL(/\/spaces\/trace/);
  const scopeText = await c.textContent("[data-testid=trace-scope]");
  check("지원 범위 명시: 외곽 형태와 문·창·기둥, 내부 벽·방문은 후속", scopeText.includes("현재 지원 범위: 실내 외곽 형태와 출입문·창·기둥 입력") && scopeText.includes("공간 안의 벽·방문(아파트·주택의 방 구조) 재현은 후속 범위"));
  await c.setInputFiles("[data-testid=trace-file]", t.fixture("trace-L.png"));
  await c.waitForSelector("[data-testid=trace-canvas]");
  check("도면 밑그림을 띄움(원본 크기 그대로)", (await c.getAttribute("[data-testid=trace-canvas]", "data-image-size")) === "1200x1000");
  await c.click("[data-testid=trace-next]");
  check("축척 전에 다음으로 못 감", (await c.textContent("[data-testid=trace-msg]")).includes("축척"));
  await clickPx(c, 100, 100); await clickPx(c, 900, 100);
  await c.fill("[data-testid=cal-mm]", "8000"); await c.click("[data-testid=cal-apply]");
  check("축척: 800px = 8,000mm → 1px = 10.0mm", (await c.textContent("[data-testid=cal-result]")).includes("10.0mm"));
  await c.click("[data-testid=scale-check]"); await clickPx(c, 100, 100); await clickPx(c, 100, 800);
  const measured = Number((await c.textContent("[data-testid=scale-check-result]")).match(/([\d,]+)mm/)[1].replaceAll(",", ""));
  check("확인용 재기: 다른 치수 7,000mm(±20mm)", Math.abs(measured - 7000) <= 20, String(measured));
  await c.click("[data-testid=scale-check]");
  await c.click("[data-testid=trace-next]");
  // 손 떨림(수직 방향 2~3px)을 넣어 찍어도 가로·세로로 맞춰진다.
  for (const [u, v] of [[100, 100], [900, 103], [902, 500], [600, 497], [603, 800], [100, 803]]) await clickPx(c, u, v);
  check("모서리 6개 찍음", (await c.textContent("[data-testid=trace-count]")).trim() === "6");
  await c.click("[data-testid=trace-undo]");
  check("한 점 지우기", (await c.textContent("[data-testid=trace-count]")).trim() === "5");
  await clickPx(c, 100, 803);
  await clickPx(c, 101, 101); // 첫 점을 다시 누르면 닫힘
  check("첫 점 누르기 → 닫힘, 벽 6개", (await c.textContent("[data-testid=trace-msg]")).includes("벽 6개로 닫았어요"));
  const lens = async () => (await c.textContent("[data-testid=trace-outline]")).match(/벽 \d+ · [\d,]+/g).map((t) => Number(t.split(" · ")[1].replaceAll(",", "")));
  const raw = await lens();
  // 화면 1px ≈ 도면 1.2px ≈ 12mm라 손으로 찍은 길이는 ±20mm 안에서 달라진다(사용자 측정·찍기 오차).
  check("찍은 벽 길이: 도면 치수와 ±20mm 안", [5000, 3000, 3000, 4000, 8000, 7000].every((v, i) => Math.abs(raw[i] - v) <= 20), JSON.stringify(raw));
  // 도면에 적힌 숫자로 맞춘다(프로그램은 넣은 숫자를 그대로 쓴다).
  await c.click("[data-testid=trace-edges] summary");
  // 벽 길이를 바꿀 칸을 누르면 함께 바뀌는 벽을 미리 보여 준다.
  await c.click("[data-testid=edge-len-0]");
  check("벽 1 칸을 누르면: 벽 2가 밀리고 벽 3 길이가 바뀐다고 미리 안내", (await c.textContent("[data-testid=edge-preview]")).includes("벽 1을 바꾸면 벽 2가 밀리고, 벽 3의 길이"), await c.textContent("[data-testid=edge-preview]"));
  check("미리보기 강조: 벽 1 바꾼 벽, 벽 2·3 함께 바뀜", (await c.getAttribute("[data-testid=edge-hl-0]", "data-kind")) === "edited" && (await c.getAttribute("[data-testid=edge-hl-1]", "data-kind")) === "affected" && (await c.getAttribute("[data-testid=edge-hl-2]", "data-kind")) === "affected" && (await c.locator("[data-testid=edge-hl-3]").count()) === 0);
  await c.fill("[data-testid=edge-len-0]", "5500"); await c.press("[data-testid=edge-len-0]", "Enter");
  await c.locator("[data-testid=trace-summary]").click({ position: { x: 5, y: 5 } }); // 칸에서 나가도 변경 표시는 남는다
  const ch = await c.textContent("[data-testid=edge-change]");
  const after1 = await lens();
  check("변경 전후 값: 벽 1 → 5,500, 벽 2 길이 그대로, 벽 3 길이 함께 바뀜", ch.includes(`${raw[0].toLocaleString("ko-KR")} → 5,500mm`) && ch.includes(`길이 그대로 ${raw[1].toLocaleString("ko-KR")}mm`) && ch.includes(`${raw[2].toLocaleString("ko-KR")} → ${after1[2].toLocaleString("ko-KR")}mm`) && after1[2] === raw[2] - (5500 - raw[0]), ch);
  check("바꾼 뒤에도 함께 바뀐 벽 강조 유지", (await c.getAttribute("[data-testid=edge-hl-2]", "data-kind")) === "affected" && (await c.locator("[data-testid=edge-len-2]").getAttribute("class")).includes("border-warn"));
  await c.click("[data-testid=edge-change-undo]");
  check("이 변경 되돌리기 → 원래 길이, 강조·변경 표시 사라짐", JSON.stringify(await lens()) === JSON.stringify(raw) && (await c.locator("[data-testid=edge-change]").count()) === 0 && (await c.locator("[data-testid^=edge-hl-]").count()) === 0);
  for (const [i, v] of [[0, 5000], [1, 3000], [3, 4000]]) { await c.fill(`[data-testid=edge-len-${i}]`, String(v)); await c.press(`[data-testid=edge-len-${i}]`, "Enter"); }
  check("도면 숫자로 맞춘 벽 길이 = 5,000·3,000·3,000·4,000·8,000·7,000", JSON.stringify(await lens()) === JSON.stringify([5000, 3000, 3000, 4000, 8000, 7000]), JSON.stringify(await lens()));
  check("면적 47.0㎡(8×7 − 3×3)", (await c.textContent("[data-testid=trace-summary]")).includes("47.0㎡"));
  check("꺾인 공간 안내: 직사각형으로 바꾸지 않음, 자동 배치 없음", (await c.textContent("[data-testid=trace-shape]")).includes("직사각형으로 바꾸지 않아요") && (await c.textContent("[data-testid=trace-shape]")).includes("현재 자동 배치 지원 범위: 직사각형 공간"));
  await c.click("[data-testid=trace-next]");
  check("출입문 없이 다음 못 감", (await c.textContent("[data-testid=trace-msg]")).includes("출입문"));
  await c.click("[data-testid=tool-door]"); await clickPx(c, 330, 800);
  check("출입문 놓음(벽 선 누르기)", (await c.locator("[data-testid=trace-door]").count()) === 1);
  await c.click("[data-testid=tool-window]"); await clickPx(c, 500, 100);
  await c.click("[data-testid=tool-water]"); await clickPx(c, 900, 300);
  await c.click("[data-testid=tool-pillar]"); await clickPx(c, 300, 300);
  await clickPx(c, 250, 650);
  check("기둥 두 개 놓음", (await c.locator("[data-testid^=trace-pillar-]").count()) === 2);
  await c.click("[data-testid=trace-undo-edit]");
  check("되돌리기: 마지막 기둥 취소", (await c.locator("[data-testid^=trace-pillar-]").count()) === 1);
  await c.click("[data-testid=tool-window]"); await clickPx(c, 300, 300);
  check("벽이 아닌 곳에 창 → 안내", (await c.textContent("[data-testid=trace-msg]")).includes("벽 선 위를"));
  await c.fill("[data-testid=trace-ent-width]", "1000"); await c.press("[data-testid=trace-ent-width]", "Enter");
  await c.fill("[data-testid=trace-area-hint]", "14.2");
  const areaText = await c.textContent("[data-testid=trace-area]");
  check("면적: 계산·입력·차이를 숫자로(‘맞아요’ 판정 없음)", areaText.includes("계산 면적47.0㎡ · 약 14.2평") && areaText.includes("입력 면적14.2평 · 46.9㎡") && (await c.textContent("[data-testid=trace-area-diff]")).includes("+0.1㎡ (+0.1%)") && !(await c.textContent("main")).includes("맞아요"), areaText);
  await c.fill("[data-testid=trace-area-hint]", "17");
  check("면적 차이가 10%를 넘으면 다시 확인 권유(판정 아님)", (await c.textContent("[data-testid=trace-area-diff]")).includes("−9.2㎡ (−16.") && (await c.textContent("[data-testid=trace-area]")).includes("차이가 10%를 넘어요"), await c.textContent("[data-testid=trace-area]"));
  await c.fill("[data-testid=trace-area-hint]", "14.2");
  await c.click("[data-testid=trace-next]");
  check("확인 단계: 평면 미리보기(같은 데이터)", (await c.locator("[data-testid=trace-preview] svg").count()) === 1 && (await c.textContent("[data-testid=trace-preview]")).includes("벽 6 · 7,000"));
  await c.fill("input[name=title]", "ㄱ자 사무실 (도면)");
  await c.fill("[data-testid=staff]", "6");
  await c.click("[data-testid=trace-submit]");
  await c.waitForURL(/\/projects\/\d+\/editor/); await c.waitForSelector("main.editor");
  const pidL = Number(c.url().match(/projects\/(\d+)/)[1]);
  const rL = roomOf(pidL);
  check("저장: 다각형 그대로(꼭짓점 6개, 직사각형 변환 없음)", rL.shape === "polygon" && rL.source === "trace" && JSON.stringify(rL.outline) === JSON.stringify([[0, 0], [5, 0], [5, 3], [8, 3], [8, 7], [0, 7]]), JSON.stringify(rL.outline));
  check("저장: 출입문 벽 1 · 약 1,850부터 폭 1,000(폭은 숫자로 고침)", rL.entrance.edge === 0 && near(rL.entrance.at, 1.85, 0.03) && rL.entrance.width === 1, JSON.stringify(rL.entrance));
  check("저장: 창(벽 5)·급배수(벽 4)·기둥", rL.windows.length === 1 && rL.windows[0].edge === 4 && near(rL.windows[0].at, 3.4, 0.03) && rL.utilities.length === 1 && rL.utilities[0].edge === 3 && near(rL.utilities[0].at, 2, 0.03) && rL.pillars.length === 1 && near(rL.pillars[0].x, 1.75, 0.03) && near(rL.pillars[0].y, 4.75, 0.03), JSON.stringify([rL.windows, rL.utilities, rL.pillars]));
  const ufid = rL.underlay?.fileId;
  check("저장: 밑그림 파일과 행렬", ufid > 0 && sql(`select category from files where id=${ufid}`) === "underlay" && near(rL.underlay.m[0], 0.01, 5e-5) && rL.underlay.iw === 1200);
  check("저장: 원본 도면은 도면 자료로 따로 보관", sql(`select count(*) from files where project_id=${pidL} and category='' and original_name='trace-L.png'`) === "1");
  check("자동 배치 없이 빈 공간에서 시작 + 이유", (await c.textContent("[data-testid=no-auto]")).includes("꺾인 공간") && (await c.locator("[data-testid^=start-]").count()) === 1);
  check("편집 평면: 다각형 외곽 + 벽 번호", (await c.locator("[data-testid=editor-plan] polygon").count()) >= 2 && (await c.textContent("[data-testid=editor-plan]")).includes("벽 4 · 4,000"));
  check("편집 평면: 도면 겹쳐 보기", (await c.locator("[data-testid=editor-underlay]").count()) === 1);
  await c.click("[data-testid=underlay-toggle]");
  check("도면 겹쳐 보기 끄기", (await c.locator("[data-testid=editor-underlay]").count()) === 0);
  check("편집 평면: 급배수 표시", (await c.locator("[data-testid=editor-water]").count()) === 1);
  await c.click("[data-testid=add-desk]");
  const pl1 = await placement(c);
  const deskL = pl1.find((x) => x[0] === "n1");
  check("가구 추가: 공간 안(빠진 칸이 아닌 곳)에 놓임", deskL && !(deskL[1] > 5 && deskL[2] < 3), JSON.stringify(deskL));
  check("가구 추가 직후 ‘공간 밖’ 없음", !(await c.textContent("[data-testid=check-issues]")).includes("공간 밖으로 나갔어요"));
  await c.fill("[data-testid=pos-x]", "6500"); await c.press("[data-testid=pos-x]", "Enter");
  await c.fill("[data-testid=pos-y]", "500"); await c.press("[data-testid=pos-y]", "Enter");
  check("빠진 칸으로 옮기면 ‘공간 밖’", (await c.textContent("[data-testid=check-issues]")).includes("공간 밖으로 나갔어요"));
  await c.fill("[data-testid=pos-x]", "1000"); await c.press("[data-testid=pos-x]", "Enter");
  await c.fill("[data-testid=pos-y]", "2000"); await c.press("[data-testid=pos-y]", "Enter");
  await c.click("[data-testid=view-3d]"); await c.waitForSelector("canvas");
  check("3D: 같은 배치로 그림", (await c.locator("canvas").count()) >= 1);
  await c.click("[data-testid=view-plan]");
  await c.click("[data-testid=editor-save]"); await c.waitForURL(/saved=2/);
  const savedL = await placement(c);
  await c.reload(); await c.waitForSelector("main.editor");
  check("저장 후 다시 열어도 같은 배치", JSON.stringify(await placement(c)) === JSON.stringify(savedL));
  await c.goto(`${B}/projects/${pidL}/plan`);
  const facts = await c.textContent("[data-testid=space-facts]");
  check("공간·배치: 실제/가정 표에 따라 그린 모양·급배수", facts.includes("도면 위에 따라 그린") && facts.includes("직사각형으로 바꾸지 않았습니다") && facts.includes("급배수 위치"));
  await c.click("[data-testid=space-plan]");
  check("치수 평면도: 다각형 + 벽 번호 + 급배수 범례", (await c.textContent("[data-testid=plan-legend]")).includes("급배수") && (await c.locator("[data-testid=plan-water]").count()) >= 1);
  await c.goto(`${B}/projects/${pidL}/info`);
  const filesText = await c.textContent("main");
  check("자료 목록: 원본 도면만(밑그림 이미지는 빼고)", filesText.includes("trace-L.png") && !filesText.includes("underlay.png"));
  const ures = await c.request.get(`${B}/files/${ufid}`);
  check("밑그림 파일: 고객은 볼 수 있음", ures.status() === 200);

  group("2. 따라 그린 공간 고치기(같은 도면 위)");
  await c.goto(`${B}/projects/${pidL}/space`);
  await c.waitForSelector("[data-testid=trace-details]");
  check("고치기: 저장된 도면과 외곽을 그대로 띄움", (await c.getAttribute("[data-testid=trace-canvas]", "data-image-size")) === "1200x1000" && (await c.textContent("[data-testid=trace-outline]")).includes("벽 6 · 7,000"));
  await c.click("[data-testid=trace-edges] summary");
  await c.fill("[data-testid=edge-len-0]", "5500"); await c.press("[data-testid=edge-len-0]", "Enter");
  check("벽 길이를 숫자로 맞춤 → 다음 벽이 밀림(면적 48.5㎡)", (await c.textContent("[data-testid=trace-summary]")).includes("48.5㎡") && (await c.textContent("[data-testid=trace-outline]")).includes("벽 3 · 2,500"));
  await c.click("[data-testid=trace-next]");
  await c.click("[data-testid=trace-submit]");
  await c.waitForURL(/\/projects\/\d+\/editor/); await c.waitForSelector("main.editor");
  const rL2 = roomOf(pidL);
  check("고친 공간: 새 버전, 같은 밑그림 이어 씀", rL2.outline[1][0] === 5.5 && rL2.underlay.fileId === ufid && Number(sql(`select count(*) from versions where project_id=${pidL}`)) === 3);
  check("고친 공간: 급배수 위치는 그대로(벽 4 시작점에서 약 2,000)", rL2.utilities[0].edge === 3 && near(rL2.utilities[0].at, rL.utilities[0].at));

  group("3. 직사각형 도면: 출입문 벽을 앞벽으로 돌려 직사각형으로, 자동 배치 가능");
  await c.goto(B + "/spaces/trace");
  await c.setInputFiles("[data-testid=trace-file]", t.fixture("trace-R.png"));
  await c.waitForSelector("[data-testid=trace-canvas]");
  await clickPx(c, 100, 100); await clickPx(c, 1100, 100);
  await c.fill("[data-testid=cal-mm]", "10000"); await c.click("[data-testid=cal-apply]");
  await c.click("[data-testid=trace-next]");
  for (const [u, v] of [[100, 100], [1100, 100], [1100, 900], [100, 900]]) await clickPx(c, u, v);
  await c.click("[data-testid=trace-close]");
  await c.click("[data-testid=tool-door]"); await clickPx(c, 100, 350);
  check("왼쪽 벽 출입문 → 공간 방향을 맞췄다는 안내", (await c.textContent("[data-testid=trace-msg]")).includes("앞벽"));
  await c.click("[data-testid=tool-water]"); await clickPx(c, 600, 100);
  check("직사각형 안내: 자동 배치에서 시작", (await c.textContent("[data-testid=trace-shape]")).includes("자동 배치에서 시작할 수 있어요"));
  await c.click("[data-testid=trace-next]");
  await c.fill("input[name=title]", "직사각형 사무실 (도면)");
  await c.fill("[data-testid=staff]", "6");
  await c.click("[data-testid=trace-submit]");
  await c.waitForURL(/\/projects\/\d+\/editor/); await c.waitForSelector("main.editor");
  const pidR = Number(c.url().match(/projects\/(\d+)/)[1]);
  const rR = roomOf(pidR);
  check("직사각형으로 저장(가로 8,000 · 세로 10,000, 출입문 앞벽 약 2,050)", rR.shape === "rect" && near(rR.width, 8, 0.03) && near(rR.depth, 10, 0.03) && near(rR.entrance.at, 2.05, 0.03) && rR.source === "trace", JSON.stringify([rR.shape, rR.width, rR.depth, rR.entrance]));
  check("급배수: 도면 위쪽 벽 → 돌린 뒤 왼쪽 벽 약 5,000", rR.utilities[0].wall === "left" && near(rR.utilities[0].at, 5, 0.03), JSON.stringify(rR.utilities));
  check("자동 배치에서 시작(시작 배치 여러 개)", (await c.locator("[data-testid^=start-]").count()) > 2 && (await c.locator("[data-testid=no-auto]").count()) === 0);
  const um = rR.underlay.m, U = (u, v) => [um[0] * u + um[2] * v + um[4], um[1] * u + um[3] * v + um[5]];
  check("밑그림도 같이 돌아감(도면 왼쪽 위 → 앞벽 왼쪽 끝, 왼쪽 아래 → 앞벽 오른쪽 끝)", near(U(100, 100)[0], 0, 0.03) && near(U(100, 100)[1], 0, 0.03) && near(U(100, 900)[0], rR.width, 0.03) && near(U(1100, 100)[1], rR.depth, 0.03), JSON.stringify([U(100, 100), U(100, 900), U(1100, 100)]));

  group("4. PDF 도면");
  await c.goto(B + "/spaces/trace");
  await c.setInputFiles("[data-testid=trace-file]", t.fixture("trace-L.pdf"));
  await c.waitForSelector("[data-testid=trace-canvas]", { timeout: 20000 });
  check("PDF 첫 쪽을 이미지로 바꿔 띄움", (await c.getAttribute("[data-testid=trace-canvas]", "data-image-size")) === "2400x2000" && (await c.textContent("[data-testid=trace-msg]")).includes("PDF 1쪽"));
  await c.setInputFiles("[data-testid=trace-file]", t.fixture("trace-L.png")).catch(() => {});
  await c.goto(B + "/spaces/trace");
  await c.setInputFiles("[data-testid=trace-file]", { name: "plan.dwg", mimeType: "application/octet-stream", buffer: Buffer.from("x") });
  check("DWG는 PDF·이미지로 바꿔 달라는 안내", (await c.textContent("[data-testid=trace-msg]")).includes("DWG"));

  group("5. 탕비 설비: 자동 제안 위치 ↔ 확인된 설비 위치");
  await c.goto(B + "/spaces/new");
  await c.click("label.intake-option:has(input[value=dims])");
  await c.click("[data-testid=wizard-next]");
  await c.fill("[data-testid=room-width]", "11000"); await c.fill("[data-testid=room-depth]", "9000");
  check("마법사: 출입문 2.5m 지원 범위 표시", (await c.textContent("[data-testid=ent-range]")).includes("현재 자동 배치 지원 범위: 출입문이 가까운 모서리에서 2,500mm 이내"));
  await c.fill('input[placeholder="예: 30"]', "30");
  const wArea = await c.textContent("[data-testid=room-area]");
  check("마법사 면적: 계산 99.0㎡ · 입력 30평 99.2㎡ · 차이 −0.2㎡(−0.2%), ‘맞아요’ 없음", wArea.includes("계산 면적99.0㎡") && wArea.includes("입력 면적30평 · 99.2㎡") && wArea.includes("−0.2㎡ (−0.2%)") && !wArea.includes("맞아요"), wArea);
  await c.click("[data-testid=add-water]");
  await c.selectOption("[data-testid=water-wall-0]", "front"); await c.fill("[data-testid=water-at-0]", "1000");
  check("마법사 미리보기: 급배수 표시", (await c.locator("[data-testid=room-preview] [data-testid=plan-water]").count()) === 1);
  await c.click("[data-testid=wizard-next]");
  await c.fill("input[name=title]", "탕비 확인 테스트"); await c.fill("[data-testid=staff]", "8");
  await c.click("[data-testid=wizard-submit]"); await c.waitForURL(/\/editor/); await c.waitForSelector("main.editor");
  const pidP = Number(c.url().match(/projects\/(\d+)/)[1]);
  check("저장: 급배수 위치(앞벽 1,000)", JSON.stringify(roomOf(pidP).utilities) === JSON.stringify([{ kind: "water", wall: "front", at: 1 }]));
  const fxItem = placementOf(pidP).items.find((it) => it.fixture);
  check("자동 배치의 탕비 설비 = 자동 제안 위치", fxItem && fxItem.fixture === "proposed" && !fxItem.locked);
  check("평면: 제안 위치는 점선 표시", (await c.locator("[data-testid=editor-plan] [data-fixture=proposed]").count()) === 1);
  check("검사: 급배수 거리 알림(현재 임시 알림 거리 직선 3,000mm)", (await c.textContent("[data-testid=check-issues]")).includes("탕비 설비와 급배수 거리 알림 (현재 임시 알림 거리 직선 3,000mm)"));
  check("거리 알림 문장: 연결 가능 여부는 판정하지 않음", (await c.textContent("[data-testid=check-issues]")).includes("연결 가능 여부는 판정하지 않으며") && (await c.textContent("[data-testid=checks]")).includes("배관 연결이 되는지는 판정하지 않습니다"));
  const farIssue = (await c.textContent("[data-testid=check-issues]")).includes("급배수 위치에서 직선");
  await c.locator(`[data-testid=item-${fxItem.id}]`).click({ force: true });
  check("선택: ‘자동 제안 위치 · 급배수 확인 전’", (await c.textContent("[data-testid=fixture-badge]")).includes("자동 제안 위치 · 급배수 확인 전"));
  const before = (await placement(c)).find((x) => x[0] === fxItem.id);
  await c.click("[data-testid=move-right]");
  check("제안 위치는 옮길 수 있음", !near((await placement(c)).find((x) => x[0] === fxItem.id)[1], before[1]));
  check("설비는 복제 안 됨", await c.locator("[data-testid=duplicate]").isDisabled());
  await c.click("[data-testid=fixture-confirm]");
  check("확인 → ‘고객이 확인한 설비 위치’(업체 확인 전), 이동 버튼 사라짐", (await c.textContent("[data-testid=fixture-badge]")).includes("고객이 확인한 설비 위치") && (await c.textContent("[data-testid=fixture-note]")).includes("업체 확인 전") && (await c.locator("[data-testid=move-right]").count()) === 0 && (await c.locator("[data-testid=delete]").count()) === 0);
  check("평면: 확인된 위치는 실선", (await c.locator("[data-testid=editor-plan] [data-fixture=confirmed]").count()) === 1);
  check("확인된 위치는 급배수 거리 검사에서 뺌", !(await c.textContent("[data-testid=check-issues]")).includes("급배수 위치에서 직선"), `far before: ${farIssue}`);
  await c.click("[data-testid=editor-save]"); await c.waitForURL(/saved=2/);
  check("저장: fixture confirmed", placementOf(pidP).items.find((it) => it.id === fxItem.id).fixture === "confirmed");
  await c.goto(`${B}/projects/${pidP}/plan`);
  check("바뀐 점: 설비 위치 확인", (await c.textContent("[data-testid=version-diff]")).includes("고객이 확인한 설비 위치"));
  const factsP = await c.textContent("[data-testid=space-facts]");
  check("실제/가정 표: 급배수(고객 확인)·탕비 설비 고객 확인 위치", factsP.includes("급배수 위치(고객 확인)") && factsP.includes("고객 확인 위치 1곳") && factsP.includes("연결 가능 여부는 판정하지 않습니다"));
  check("실제/가정 표: 공간 안의 벽·방문 = 후속 범위", factsP.includes("공간 안의 벽·방문") && factsP.includes("후속 범위"));
  await c.goto(`${B}/projects/${pidP}/editor`); await c.waitForSelector("main.editor");
  await c.locator(`[data-testid=item-${fxItem.id}]`).click({ force: true });
  await c.click("[data-testid=fixture-unconfirm]");
  check("확인 풀기 → 다시 자동 제안 위치", (await c.textContent("[data-testid=fixture-badge]")).includes("자동 제안 위치"));
  check("편집 안내: 문 앞 750mm(현재 임시 검사값)", (await c.textContent("main.editor")).includes("750mm(현재 임시 검사값)"));

  group("6. 휴대폰: 가구 추가·편집 우선, 검사 상세 접기");
  const m = await ctx({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
  await login(m, "customer@demo.kr");
  await m.goto(`${B}/projects/${pidP}/editor`); await m.waitForSelector("main.editor");
  check("휴대폰: 가로 넘침 없음", (await m.evaluate(() => document.documentElement.scrollWidth)) <= 390);
  const planBox = await m.locator("[data-testid=plan-scroll]").boundingBox();
  const addBox = await m.locator("[data-testid=add-bar-m]").boundingBox();
  const chkBox = await m.locator("[data-testid=checks-m]").boundingBox();
  check("휴대폰: 가구 추가가 평면 바로 아래", addBox && addBox.y > planBox.y + planBox.height - 1 && addBox.y - (planBox.y + planBox.height) < 140, JSON.stringify([planBox, addBox]));
  check("휴대폰: 검사는 가구 추가 아래, 접혀 있음", chkBox.y > addBox.y && !(await m.getAttribute("[data-testid=checks-m]", "open") !== null) && !(await m.locator("[data-testid=checks-m] [data-testid=check-issues]").isVisible()));
  check("휴대폰: 접힌 검사 제목에 확인할 것 개수", (await m.textContent("[data-testid=checks-m] summary")).includes("자동 검사"));
  check("휴대폰: 편집 안내(가구를 누르면 버튼)", await m.locator("[data-testid=edit-hint-m]").isVisible());
  check("휴대폰: PC용 가구 목록은 숨김", !(await m.locator("[data-testid=add-desk]").isVisible()) && (await m.locator("[data-testid=save-info-m]").getAttribute("open")) === null);
  const n0 = (await placement(m)).length;
  await m.tap("[data-testid=add-m-desk]");
  check("휴대폰: 가구 추가 → 바로 선택되고 조작판 열림", (await placement(m)).length === n0 + 1 && (await m.locator(".editor-sheet.is-open [data-testid=rotate]").isVisible()));
  await m.tap("[data-testid=rotate]");
  check("휴대폰: 조작판에서 돌리기", (await placement(m)).at(-1)[3] === 270);
  await m.tap(".editor-sheet.is-open >> text=선택 해제");
  await m.tap("[data-testid=checks-m] summary");
  check("휴대폰: 검사 펼치기", await m.locator("[data-testid=checks-m] [data-testid=check-issues]").isVisible());
  await m.goto(B + "/spaces/trace");
  check("휴대폰: 따라 그리기는 PC 안내", await m.locator("[data-testid=trace-pc]").isVisible());
  check("휴대폰: 따라 그리기 화면도 가로 넘침 없음", (await m.evaluate(() => document.documentElement.scrollWidth)) <= 390);

  group("7. 꺾인 공간도 업체 화면·인쇄에서 같은 모양");
  await c.goto(`${B}/projects/${pidL}/print`).catch(() => {});
  check("인쇄: 다각형 평면 + 벽 번호", (await c.textContent("body")).includes("벽 6 ·"));
  await requestSpace(c, B, pidL, { region: "서울 성동구", budgetMin: 3000, budgetMax: 5000 });
  const snapL = JSON.parse(sql(`select snapshot from request_revisions where project_id=${pidL} and no=1`));
  check("요청 기록: 다각형 구조 그대로 고정", snapL.layout.room.shape === "polygon" && snapL.layout.room.outline.length === 6);
  const admin = await ctx(); await login(admin, "admin@demo.kr");
  await admin.goto(`${B}/admin/projects/${pidL}`);
  await admin.locator(`label:has-text("[예시] 스튜디오 온결") input[name=vendor]`).check();
  await admin.click('button:has-text("선택한 업체 배정")'); await admin.waitForSelector("text=업체 1곳을 배정했습니다");
  const v = await ctx(); await login(v, "vendor1@demo.kr");
  const aid = sql(`select a.id from assignments a join vendors x on x.id=a.vendor_id join users u on u.id=x.user_id where a.project_id=${pidL} and u.email='vendor1@demo.kr'`);
  await v.goto(`${B}/vendor/requests/${aid}`);
  check("업체 화면: 도면 따라 그린 공간이라고 안내", (await v.textContent("[data-testid=sent-layout]")).includes("도면 위에 따라 그려 만든 공간"));
  await v.click("[data-testid=sent-layout] [data-testid=space-plan]");
  const sentText = await v.textContent("[data-testid=sent-layout]");
  check("업체 화면: 받은 배치가 꺾인 모양 그대로(벽 번호·급배수)", sentText.includes("벽 6 ·") && sentText.includes("급배수"), sentText.slice(0, 200));
  check("업체 화면: 실제/가정 표에 따라 그린 모양·내부 벽 후속 범위", (await v.textContent("main")).includes("직사각형으로 바꾸지 않았습니다") && (await v.textContent("main")).includes("공간 안의 벽·방문"));
  const ul = await v.request.get(`${B}/files/${ufid}`);
  check("업체 화면: 공간 이름 없음", !(await v.textContent("main")).includes("ㄱ자 사무실 (도면)"), String(ul.status()));
});
