// 독립 시연 DB에서 수정한 가격·환불·교환·커뮤니티 연결을 실제 UI로 검증한다.
const {chromium}=require('playwright-core');
const {DatabaseSync}=require('node:sqlite');
const fs=require('node:fs'),path=require('node:path');
const B=process.env.B,DB=process.env.DB;
if (!B || !DB || !DB.includes('.e2e-data')) throw new Error('분리된 E2E 서버·데이터만 사용할 수 있습니다.');
const db=new DatabaseSync(DB);db.exec('PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000');
const get=(s,...p)=>db.prepare(s).get(...p),run=(s,...p)=>Number(db.prepare(s).run(...p).lastInsertRowid);
const OUT=process.env.OUT || path.join(process.env.P || process.cwd(),'.e2e-data/shots/v2-fixes');fs.mkdirSync(OUT,{recursive:true});
const results=[];const errors=[];
const check=(name,ok,detail='')=>{const line=`${ok?'PASS':'FAIL'} ${name}${ok?'':` — ${JSON.stringify(detail)}`}`;results.push(line);console.log(line);};
const until=async(f)=>{for(let i=0;i<120;i++){if(f())return;await new Promise(r=>setTimeout(r,100));}throw new Error('저장 결과를 기다리다 시간 초과');};
const shot=(p,n)=>p.screenshot({path:path.join(OUT,n+'.png'),fullPage:true});
let browser;
(async()=>{
  browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=async(email,mobile=false)=>{
    const p=await(await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile})).newPage();
    p.on('pageerror',e=>errors.push(e.message));
    if(email){await p.goto(B+'/login');await p.fill('[name=email]',email);await p.fill('[name=password]','demo1234');await p.getByRole('button',{name:'로그인',exact:true}).click();await p.waitForURL(u=>u.pathname!='/login');}
    return p;
  };
  const customer=get("SELECT id FROM users WHERE email='customer@demo.kr'").id;
  const seller=get("SELECT s.id FROM sellers s JOIN users u ON u.id=s.user_id WHERE u.email='seller@demo.kr'").id;
  function fixture(qty=1,ship=3000,status='delivered') {
    const product=run("INSERT INTO products(seller_id,title,category,price,status,option1_name,width_mm,depth_mm,height_mm) VALUES (?,'E2E 교환 상품','deco',10000,'on_sale','옵션',1000,400,700)",seller);
    const sku=run("INSERT INTO product_skus(product_id,opt1,stock) VALUES (?,'기본',20)",product);
    const target=run("INSERT INTO product_skus(product_id,opt1,stock,add_price) VALUES (?,'큰 옵션',5,5000)",product);
    const no=`FIX-${Date.now()}-${product}`;
    const order=run("INSERT INTO orders(no,user_id,status,title,items_amount,ship_amount,total_amount,recipient,phone,address1,pg,payment_key) VALUES (?,?,'paid','E2E 수정 검증',?,?,?,'고객','01012345678','외부 공개 금지 주소','test','synthetic')",no,customer,qty*10000,ship,qty*10000+ship);
    const group=run("INSERT INTO order_groups(order_id,seller_id,ship_fee,status,shipping_policy) VALUES (?,?,?,?,?)",order,seller,ship,status,JSON.stringify({ship_fee:3000,free_ship_over:30000,return_fee:3000}));
    const item=run("INSERT INTO order_items(order_id,group_id,product_id,sku_id,title,option_text,unit_price,qty,amount) VALUES (?,?,?,?,'E2E 교환 상품','기본',10000,?,?)",order,group,product,sku,qty,qty*10000);
    return {product,sku,target,no,order,group,item};
  }
  const c=await page('customer@demo.kr',true),s=await page('seller@demo.kr',true),a=await page('admin@demo.kr');
  await s.goto(B+'/seller/products/new');await s.fill('[name=title]','음수 옵션 차단');await s.selectOption('[name=category]','deco');await s.fill('[name=price]','10000');await s.getByLabel('추가 금액',{exact:true}).fill('-20000');await s.getByLabel('재고',{exact:true}).fill('5');await s.setInputFiles('[data-testid=product-images]',__dirname+'/fixtures/photo1.jpg');await s.click('[data-testid=product-publish]');await s.waitForSelector('main [role=alert]');
  check('판매자 음수 최종 가격 등록 차단',!(get("SELECT id FROM products WHERE title='음수 옵션 차단'")) && (await s.textContent('main [role=alert]')).includes('최종 판매가'));
  await shot(s,'negative-price-blocked');
  const partial=fixture(3,0,'paid');
  for(let n=1;n<=3;n++){
    await c.goto(B+'/orders/'+partial.no);await c.click('[data-testid=cancel-open]');await c.selectOption('select[name=qty]','1');await c.selectOption('[data-testid=cancel-reason]','change_mind');await c.locator('form').filter({has:c.locator('select[name=qty]')}).getByRole('button',{name:'주문 취소',exact:true}).click();await until(()=>get("SELECT count(*) AS n FROM claims WHERE order_id=? AND status='completed'",partial.order).n===n);
  }
  check('휴대폰 분할 취소 누적 환불 30,000원',get('SELECT sum(refund_amount) AS n FROM claims WHERE order_id=?',partial.order).n===30000);
  await c.reload();await shot(c,'partial-cancel-full-refund');
  const defect=fixture();await c.goto(B+'/orders/'+defect.no);await c.click('[data-testid=return-open]');await c.selectOption('[data-testid=return-reason]','defect');await c.locator('form').filter({has:c.locator('[data-testid=return-reason]')}).getByRole('button',{name:'반품 신청',exact:true}).click();await until(()=>get('SELECT id FROM claims WHERE order_id=?',defect.order));
  const claim=get('SELECT id FROM claims WHERE order_id=?',defect.order).id;
  await s.goto(B+'/seller/claims');await s.locator(`[data-claim="${claim}"]`).getByRole('button',{name:'반품 승인(회수 진행)',exact:true}).click();await until(()=>get('SELECT status FROM claims WHERE id=?',claim).status==='approved');await s.reload();await s.locator(`[data-claim="${claim}"]`).getByRole('button',{name:'회수 확인·환불',exact:true}).click();await until(()=>get('SELECT status FROM claims WHERE id=?',claim).status==='completed');
  check('판매자 불량 전량 반품 배송비 포함 13,000원',get('SELECT refund_amount FROM claims WHERE id=?',claim).refund_amount===13000);
  const ex=fixture();await c.goto(B+'/orders/'+ex.no);await c.click('[data-testid=exchange-open]');await c.selectOption('[data-testid=exchange-sku]',String(ex.target));await c.selectOption('[data-testid=exchange-reason]','change_mind');await c.getByRole('button',{name:'교환 요청 보내기',exact:true}).click();await until(()=>get('SELECT id FROM exchanges WHERE order_id=?',ex.order));
  const eid=get('SELECT id FROM exchanges WHERE order_id=?',ex.order).id;
  check('고객 교환 신청 저장·구매 확정 숨김',get('SELECT status FROM exchanges WHERE id=?',eid).status==='requested' && await c.locator('[data-testid=confirm-purchase]').count()===0);
  await s.goto(B+'/seller/exchanges');await s.locator(`[data-exchange="${eid}"]`).getByRole('button',{name:'교환 승인',exact:true}).click();await until(()=>get('SELECT status FROM exchanges WHERE id=?',eid).status==='approved');
  check('판매자 승인·차액 11,000원·재고 예약',get('SELECT amount_due FROM exchanges WHERE id=?',eid).amount_due===11000 && get('SELECT stock FROM product_skus WHERE id=?',ex.target).stock===4);
  await s.reload();await s.locator(`[data-exchange="${eid}"]`).getByRole('button',{name:'회수 확인·차액 처리',exact:true}).click();await until(()=>get('SELECT status FROM exchanges WHERE id=?',eid).status==='collected');
  await a.goto(B+'/admin/exchanges');check('운영자 교환 진행 조회',await a.locator(`[data-exchange="${eid}"]`).count()===1);
  await c.goto(B+'/orders/'+ex.no);await c.click('[data-testid=exchange-pay]');await c.waitForURL(/\/pay\//);check('교환 결제 화면 서버 계산 금액 11,000원',(await c.textContent('main')).includes('11,000원'));
  await c.click('[data-testid=test-pay-ok]');await c.waitForURL(/\/orders\//);await c.click('[data-testid=exchange-parent]');await c.waitForURL(B+'/orders/'+ex.no);
  check('추가 결제 후 교환 발송 준비로 변경',get('SELECT status FROM exchanges WHERE id=?',eid).status==='ready');
  await s.goto(B+'/seller/exchanges');const box=s.locator(`[data-exchange="${eid}"]`);await box.locator('[name=courier]').fill('CJ대한통운');await box.locator('[name=tracking_no]').fill('123456');await box.getByRole('button',{name:'교환 상품 발송',exact:true}).click();await until(()=>get('SELECT status FROM exchanges WHERE id=?',eid).status==='shipped');
  await c.goto(B+'/orders/'+ex.no);check('재발송 송장·교환 받은 옵션 표시',(await c.textContent('[data-testid=exchanges]')).includes('123456') && (await c.textContent('main')).includes('교환받은 상품'));
  await c.click('[data-testid=exchange-received]');await until(()=>get('SELECT status FROM exchanges WHERE id=?',eid).status==='completed');await c.reload();check('고객 교환 수령 확인 후 구매 확정 가능',await c.locator('[data-testid=confirm-purchase]').count()===1);
  check('교환 휴대폰 가로 넘침 없음',await c.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot(c,'exchange-completed-mobile');
  await c.goto(B+'/community/new?project=1');check('내 공간에서 글쓰기 시작 시 프로젝트 미리 선택',await c.inputValue('[data-testid=post-project]')==='1');await c.fill('[data-testid=post-title]','내 공간을 소개합니다');await c.setInputFiles('[data-testid=post-photos]',__dirname+'/fixtures/photo1.jpg');await c.click('[data-testid=post-submit]');await c.waitForURL(/\/community\/\d+$/);
  const postId=Number(c.url().split('/').pop());check('일반 게시물 내 공간 연결·계약 확인 미표시',get('SELECT project_id FROM posts WHERE id=?',postId).project_id===1 && get('SELECT verified FROM posts WHERE id=?',postId).verified===0);
  await c.goto(B+'/projects/1');check('내 공간에 작성한 게시물 연결',await c.locator(`[data-testid=project-posts] a[href="/community/${postId}"]`).count()===1);
  const publicPage=await page();await publicPage.goto(B+'/community/'+postId);check('공개 게시물에서 작성자 내부 프로젝트·주소 비공개',await publicPage.locator('[data-testid=post-own-space]').count()===0 && !(await publicPage.textContent('main')).includes('외부 공개 금지 주소'));
  const photo=get('SELECT id FROM post_photos WHERE post_id=?',postId).id;
  await c.goto(B+'/community/'+postId);await c.click('[data-testid=reference-photo]');await c.waitForURL(/\/spaces\/new/);check('고른 사진을 가진 공간 만들기 화면으로 연결',c.url().includes(`postPhoto=${photo}`) && await c.locator('[data-testid=reference-post]').count()===1);
  await c.locator('label').filter({has:c.locator('input[name=intakeChoice][value=dims]')}).click();await c.click('[data-testid=wizard-next]');await c.fill('[data-testid=room-width]','11000');await c.fill('[data-testid=room-depth]','9000');await c.click('[data-testid=wizard-next]');await c.click('[data-testid=wizard-submit]');await c.waitForURL(/\/projects\/\d+/);
  const project=Number(c.url().match(/projects\/(\d+)/)[1]);
  check('새 공간에 선택한 게시물과 사진 저장',get('SELECT count(*) AS n FROM project_post_refs WHERE project_id=? AND post_id=? AND photo_id=?',project,postId,photo).n===1);
  await c.goto(B+'/projects/'+project+'/info');check('고객 참고 사진 표시',(await c.textContent('[data-testid=post-references]')).includes('내 공간을 소개합니다'));
  await a.goto(B+'/admin/projects/'+project);check('운영자 참고 사진 표시',await a.locator('[data-testid=post-references]').count()===1);
  await c.goto(B+'/projects/'+project+'/request');await c.fill('[data-testid=req-region]','서울 성동구');await c.fill('[name=address]','공유 금지 고객 주소');await c.click('[data-testid=req-send]');await until(()=>get('SELECT count(*) AS n FROM request_revisions WHERE project_id=?',project).n===1);
  const revision=JSON.parse(get('SELECT snapshot FROM request_revisions WHERE project_id=?',project).snapshot);
  check('실제 요청 전송에 참고 게시물·고른 사진 포함',revision.postRefs[0].postId===postId && revision.postRefs[0].photoId===photo);
  const vendor=get("SELECT v.id FROM vendors v JOIN users u ON u.id=v.user_id WHERE u.email='vendor1@demo.kr'").id;
  await a.goto(B+'/admin/projects/'+project);await a.check(`input[name=vendor][value="${vendor}"]`);await a.getByRole('button',{name:'선택한 업체 배정',exact:true}).click();await until(()=>get('SELECT id FROM assignments WHERE project_id=? AND vendor_id=?',project,vendor));
  const assignment=get('SELECT id FROM assignments WHERE project_id=? AND vendor_id=?',project,vendor).id;
  const v=await page('vendor1@demo.kr',true);await v.goto(B+'/vendor/requests/'+assignment);
  check('시공사 참고 게시물·사진 수신 및 상세 주소 비공개',await v.locator('[data-testid=post-references]').count()===1 && !(await v.textContent('main')).includes('공유 금지 고객 주소'));
  await c.goto(B+'/projects/'+project+'/info');await c.getByRole('button',{name:'참고 게시물 연결 해제',exact:true}).click();await until(()=>get('SELECT count(*) AS n FROM project_post_refs WHERE project_id=?',project).n===0);
  await v.reload();check('고객이 해제해도 전송 전 시공사 기준 사진 유지',await v.locator('[data-testid=post-references]').count()===1);
  await c.goto(B+'/projects/'+project);await c.click('[data-testid=send-update]');await until(()=>get('SELECT count(*) AS n FROM request_revisions WHERE project_id=?',project).n===2);
  await v.reload();check('변경 전송 후 새 기준에서 참고 사진 해제 반영',await v.locator('[data-testid=post-references]').count()===0);
  check('r1 요청 기록에는 원래 참고 사진 보존',JSON.parse(get('SELECT snapshot FROM request_revisions WHERE project_id=? AND no=1',project).snapshot).postRefs[0].photoId===photo);
  await c.goto(B+'/homes/new');await c.click('[data-testid=home-type-apartment]');await c.fill('[data-testid=home-region]','서울 마포구');await c.click('[data-testid=home-next]');await c.click('[data-testid=home-scope-undecided]');await c.click('[data-testid=home-next]');await c.click('[data-testid=home-next]');await c.click('[data-testid=home-save]');await c.waitForURL(/\/projects\/\d+$/);
  const houseProject=Number(c.url().split('/').pop());
  await c.goto(`${B}/projects/${houseProject}/house/new?from=dims`);await c.fill('[data-testid=house-w]','8000');await c.fill('[data-testid=house-d]','6000');await c.click('[data-testid=house-submit]');await c.waitForURL(/house\/edit/);
  const savedHouse=()=>JSON.parse(get('SELECT house FROM versions WHERE id=(SELECT current_version_id FROM projects WHERE id=?)',houseProject).house);
  await c.goto(`${B}/projects/${houseProject}/house/edit?add=product:${ex.product}:${ex.sku}`);await c.waitForSelector('[data-testid=placed-product]');await c.click('[data-testid=editor-save]');await until(()=>savedHouse().items.length===1);
  run('UPDATE products SET width_mm=2000,height_mm=900,price=20000 WHERE id=?',ex.product);
  await c.goto(`${B}/projects/${houseProject}/house/edit`);await c.click('[data-testid=mode-furniture]');await c.locator('[data-hit=item]').first().click();const initialX=savedHouse().items[0].x;await c.click('[data-testid=move-right]');await c.click('[data-testid=editor-save]');await until(()=>savedHouse().items[0].x>initialX);
  check('브라우저 저장: 판매자 규격 변경 후 기존 폭·높이 유지',savedHouse().items[0].w===1 && savedHouse().items[0].product.h===.7);
  await c.goto(`${B}/projects/${houseProject}/house/edit`);await c.click('[data-testid=mode-furniture]');await c.locator('[data-hit=item]').first().click();
  check('편집기 가격은 저장 당시 금액이라고 표시',(await c.textContent('[data-testid=placed-product]')).includes('저장 당시 10,000원'));
  run("UPDATE products SET status='deleted' WHERE id=?",ex.product);
  await c.goto(`${B}/projects/${houseProject}/house/edit`);await c.click('[data-testid=mode-furniture]');await c.locator('[data-hit=item]').first().click();const xBefore=savedHouse().items[0].x;await c.click('[data-testid=move-right]');await c.click('[data-testid=editor-save]');await until(()=>savedHouse().items[0].x>xBefore);
  check('브라우저 저장: 삭제된 상품을 옮겨도 배치 저장 성공',savedHouse().items[0].w===1);
  await c.click('[data-testid=view-3d]');await c.waitForSelector('canvas[data-viewer="3d"]');check('삭제된 상품도 저장한 규격으로 3D 표시',await c.locator('canvas[data-viewer="3d"]').count()===1);await shot(c,'deleted-product-3d-mobile');
  await c.goto(B+'/request?post='+postId+'&postPhoto='+photo);check('상담 요청도 참고 게시물 유지',(await c.getByRole('link',{name:'집',exact:false}).getAttribute('href')).includes('postPhoto='+photo));
  check('브라우저 JS 오류 없음',errors.length===0,errors);check('외래 키 무결성',db.prepare('PRAGMA foreign_key_check').all().length===0);
  fs.writeFileSync(path.join(OUT,'checks.json'),JSON.stringify(results,null,2));
})().catch(e=>{check('E2E 실행 중단',false,e.stack);}).finally(async()=>{if(browser)await browser.close();db.close();const failures=results.filter(r=>r.startsWith('FAIL')).length;console.log(`\n${results.length-failures} passed, ${failures} failed`);process.exitCode=failures?1:0;});
