// Explicit real/free API test of the intake flow. Use an isolated server and DB only.
/* eslint-disable @typescript-eslint/no-require-imports -- Uses the repository's CommonJS E2E harness. */
const fs = require("node:fs");
const path = require("node:path");
const { suite } = require("../e2e/lib/harness.cjs");
if (!process.env.DB || !path.resolve(process.env.DB).includes(`${path.sep}.e2e-data${path.sep}`)) throw new Error("Use an isolated .e2e-data DB");
const t = suite("intake-live", { webgl: false });
const keys = fs.readFileSync(path.join(t.P, ".env.local"), "utf8").split(/\r?\n/).filter((line) => /^(JUSO(?:_DETAIL)?_API_KEY|DATA_GO_KR_KEY)=/.test(line)).map((line) => line.slice(line.indexOf("=") + 1).trim().replace(/^['"]|['"]$/g, ""));
const logFile = path.join(t.P, ".e2e-data", "intake-live.out");
fs.writeFileSync(logFile, "");
const print = console.log;
console.log = (...args) => { fs.appendFileSync(logFile, args.join(" ") + "\n"); print(...args); };
const findUnit = async (p) => {
  await p.fill("[data-testid=addr-q]", "구리시 산마루로 46");
  await p.press("[data-testid=addr-q]", "Enter");
  await p.locator("[data-testid=addr-hits] button").first().waitFor();
  await p.locator("[data-testid=addr-hits] button").first().click();
  await p.locator("[data-testid=addr-dong] option[value='401동']").waitFor({ state: "attached" });
  await p.selectOption("[data-testid=addr-dong]", "401동");
  await p.locator("[data-testid=addr-floor] option[value='1층']").waitFor({ state: "attached" });
  await p.selectOption("[data-testid=addr-floor]", "1층");
  await p.selectOption("[data-testid=addr-ho]", "102호");
};
const building = async (p) => {
  await p.click("[data-testid=addr-building]");
  await p.locator("[data-testid=addr-unit]").filter({ hasText: "74.94" }).waitFor();
};
const pidOf = (p) => Number(p.url().match(/projects\/(\d+)/)[1]);
t.run(async () => {
  const pc = await t.page();
  pc.setDefaultTimeout(60_000);
  await t.login(pc, "customer@demo.kr");
  await pc.goto(t.B + "/projects/new?intake=none");
  t.check("기존 신청 첫 화면에 집·사무실 선택과 주소 조회를 바로 표시", await pc.locator("[data-testid=intake-kind-home]").isVisible() && await pc.locator("[data-testid=addr-q]").isVisible());
  t.check("사무실만 접수한다는 낡은 안내 제거", !(await pc.textContent("main")).includes("지금은 사무실만 받고 있어요"));
  t.check("신청 폼 안에 검색 폼을 중첩하지 않음", await pc.locator("main form").count() === 1 && await pc.locator("main form form").count() === 0);
  const beforeOffice = t.sql("select count(*) from projects");
  await findUnit(pc);
  t.check("주소 검색 Enter로 다음 단계나 신청 제출이 실행되지 않음", await pc.locator("[data-testid=intake]").isVisible() && t.sql("select count(*) from projects") === beforeOffice);
  await building(pc);
  t.check("조회만으로 기존 신청 값을 덮어쓰지 않음", await pc.inputValue("input[name=areaPyeong]") === "30");
  await pc.click("[data-testid=addr-apply]");
  t.check("기존 사무실 신청서에 지역·호 주소·전용 평수 반영", await pc.inputValue("input[name=region]") === "경기도 구리시" && (await pc.inputValue("input[name=address]")).includes("401동 102호") && await pc.inputValue("input[name=areaPyeong]") === "22.7");
  t.check("실측 치수와 가정 도면은 자동으로 만들지 않음", await pc.locator("input[name=widthM]").count() === 0 && await pc.locator("aside svg[aria-label$='평면도']").count() === 0);
  await t.shot(pc, "01-office-intake");
  for (let i = 0; i < 6; i++) await pc.getByRole("button", { name: "다음", exact: true }).click();
  await pc.fill("input[name=title]", "주소 불러오기 검증 사무실");
  await pc.getByRole("button", { name: "요청 등록하기", exact: true }).click();
  await pc.waitForURL(/\/projects\/\d+$/);
  const office = pidOf(pc);
  const officeInput = JSON.parse(t.sql(`select input from versions where project_id=${office} order by no desc limit 1`));
  t.check("저장된 사무실 요청에도 불러온 정보와 치수 미입력 유지", t.sql(`select region||'|'||address from projects where id=${office}`).includes("401동 102호") && officeInput.areaPyeong === 22.7 && officeInput.widthM === null && officeInput.depthM === null);

  await pc.goto(t.B + "/spaces/new");
  t.check("사무실 공간 만들기 첫 단계에도 같은 주소 조회 표시", await pc.locator("[data-testid=addr-q]").isVisible());
  await findUnit(pc); await building(pc); await pc.click("[data-testid=addr-apply]");
  t.check("공간 만들기는 조회 면적만 참고하고 가로·세로를 비워 둠", await pc.inputValue("[data-testid=room-width]") === "" && await pc.inputValue("[data-testid=room-depth]") === "");
  await pc.click('label.intake-option:has(input[value=dims])');
  await pc.click("[data-testid=wizard-next]");
  await pc.fill("[data-testid=room-width]", "11000"); await pc.fill("[data-testid=room-depth]", "9000");
  await pc.click("[data-testid=wizard-next]");
  t.check("공간 만들기의 마지막 단계에도 불러온 지역 유지", await pc.inputValue("input[name=region]") === "경기도 구리시");
  await pc.click("[data-testid=wizard-submit]"); await pc.waitForURL(/\/projects\/\d+\/editor/);
  const space = pidOf(pc);
  t.check("직접 입력한 치수로 저장하며 불러온 상세 주소도 보존", t.sql(`select address from projects where id=${space}`).includes("401동 102호") && JSON.parse(t.sql(`select room from versions where project_id=${space} order by no desc limit 1`)).width === 11);

  const homeIds = [];
  for (const mobile of [false, true]) {
    const mode = mobile ? "휴대폰" : "PC";
    const p = mobile ? await t.phone() : await t.page();
    p.setDefaultTimeout(60_000);
    let calls = 0, leaked = false;
    p.on("request", (r) => { if (/business\.juso\.go\.kr|apis\.data\.go\.kr/.test(r.url())) calls++; if (keys.some((k) => r.url().includes(k))) leaked = true; });
    await t.login(p, "customer@demo.kr");
    await p.goto(t.B + "/projects/new"); await p.click("[data-testid=intake-kind-home]"); await p.waitForURL(/\/homes\/new$/);
    t.check(`${mode} 같은 신청 흐름에서 집 유형으로 전환`, await p.locator("[data-testid=addr-q]").isVisible() && await p.locator("[data-testid=home-type-apartment]").isVisible());
    await p.click("[data-testid=home-type-apartment]");
    await p.fill("[data-testid=home-area]", "99"); await p.fill("[data-testid=home-region]", "서울 마포구");
    const before = t.sql("select count(*) from projects");
    await findUnit(p);
    t.check(`${mode} 검색 Enter는 조회만 실행하고 신청 단계를 유지`, await p.locator("[data-testid=home-step-1].is-on").count() === 1 && t.sql("select count(*) from projects") === before);
    await p.click("[data-testid=addr-apply]");
    t.check(`${mode} 주소만 확인했을 때 면적을 임의로 채우지 않음`, await p.inputValue("[data-testid=home-area]") === "" && await p.inputValue("[data-testid=home-area-basis]") === "unknown");
    await building(p); await p.click("[data-testid=addr-apply]");
    t.check(`${mode} 같은 화면에서 전용면적 74.94㎡와 기준을 채움`, await p.inputValue("[data-testid=home-area]") === "74.94" && await p.inputValue("[data-testid=home-area-unit]") === "m2" && await p.inputValue("[data-testid=home-area-basis]") === "exclusive");
    t.check(`${mode} 지역·상세주소·사용승인 연도 전달`, await p.inputValue("[data-testid=home-region]") === "경기도 구리시" && (await p.inputValue("input[name=address]")).includes("401동 102호") && await p.inputValue("[data-testid=home-year]") === "2017");
    t.check(`${mode} 유형은 고객 선택을 유지하고 방·욕실은 추측하지 않음`, await p.locator("[data-testid=home-type-apartment] input").isChecked() && await p.inputValue("[data-testid=home-rooms]") === "" && await p.inputValue("[data-testid=home-baths]") === "");
    t.check(`${mode} 신청 폼 하나와 가로 넘침 없음`, await p.locator("main form").count() === 1 && await t.noOverflow(p));
    const html = await p.content();
    t.check(`${mode} 키 노출·브라우저에서 외부 API 직접 호출 없음`, calls === 0 && !leaked && !keys.some((k) => html.includes(k)));
    await t.shot(p, mobile ? "03-home-mobile" : "02-home-desktop");
    await p.click("[data-testid=home-next]"); await p.click("[data-testid=home-scope-undecided]");
    await p.click("[data-testid=home-next]");
    t.check(`${mode} 도면 업로드와 자료 없이 상담 경로 유지`, await p.locator("[data-testid=home-drawings]").isVisible() && await p.locator("[data-testid=home-no-files]").isVisible());
    await p.click("[data-testid=home-next]");
    t.check(`${mode} 다음 단계에서도 불러온 상세주소 유지`, (await p.inputValue("input[name=address]")).includes("401동 102호"));
    await p.check("[data-testid=bid-open]"); await p.click("[data-testid=home-send]"); await p.waitForURL(/\/projects\/\d+$/);
    const id = pidOf(p); homeIds.push(id);
    const input = JSON.parse(t.sql(`select input from versions where project_id=${id} order by no desc limit 1`));
    t.check(`${mode} 제출 후 다시 열어도 API 면적·단위·기준 유지`, input.area === 74.94 && input.areaUnit === "m2" && input.areaBasis === "exclusive" && input.builtYear === 2017 && t.sql(`select address from projects where id=${id}`).includes("401동 102호"));
    t.check(`${mode} 자료 없는 집 요청에 가정 3D를 생성하지 않음`, t.sql(`select count(*) from versions where project_id=${id} and house is not null`) === "0");
    await p.context().close();
  }
  const admin = await t.page(); await t.login(admin, "admin@demo.kr"); await admin.goto(`${t.B}/admin/projects/${homeIds[0]}`);
  t.check("운영자도 제출된 전용면적을 확인할 수 있음", (await admin.textContent("main")).includes("74.94"));
  const vendor = await t.page(); await t.login(vendor, "vendor2@demo.kr"); await vendor.goto(`${t.B}/vendor/open/${homeIds[0]}`);
  const publicRequest = await vendor.textContent("main");
  t.check("업체 미리보기에서 고객의 동·호를 공개하지 않음", publicRequest.includes("구리시") && !publicRequest.includes("401동") && !publicRequest.includes("102호"));
  const logs = t.sql("select query||' '||result from ext_lookups where kind in ('building','juso-detail')");
  t.check("API 조회 기록에 선택 동·호와 인증키 없음", !logs.includes("401동") && !logs.includes("102호") && !keys.some((k) => logs.includes(k)));
});
