# -*- coding: utf-8 -*-
from pathlib import Path
import json
root=Path(__file__).resolve().parent.parent
out=root/'output'
svg=(out/'01_치수평면도.svg').read_text()
bundle=(root/'source/viewer.bundle.js').read_text()
data=(out/'layout-data.json').read_text()
page='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>30평 사무실 · 공간 배치 A안</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f5ee;color:#263e33;font-family:"Apple SD Gothic Neo","Malgun Gothic",sans-serif}header{padding:28px 36px 23px;display:flex;align-items:end;justify-content:space-between;background:#fafaf6;border-bottom:1px solid #d6dcd2}.kicker{font-size:11px;letter-spacing:3px;color:#748275;margin-bottom:8px}h1{font-size:28px;letter-spacing:-1px;margin:0}header p{margin:9px 0 0;color:#738074;font-size:13px}.badge{font-size:12px;border:1px solid #9daa99;padding:9px 14px;border-radius:20px}main{display:grid;grid-template-columns:minmax(0,1fr) 280px;height:calc(100vh - 137px);min-height:630px}section{position:relative;overflow:hidden}#view{display:block;width:100%;height:100%;outline:none}.tools{position:absolute;left:24px;top:20px;display:flex;gap:7px;flex-wrap:wrap}button{background:#fffdf6;border:1px solid #c8d1c4;border-radius:7px;padding:10px 14px;color:#294235;cursor:pointer;font:inherit;font-size:12px}button:hover{background:#dde7d9}.hint{position:absolute;bottom:22px;left:24px;font-size:12px;color:#6c796c;background:#fafaf4de;padding:10px 14px;border-radius:6px}aside{background:#fafaf6;padding:26px 22px;border-left:1px solid #d6dcd2;overflow:auto}aside h2{font-size:13px;margin:0 0 18px}.area{font-size:35px;font-weight:600;letter-spacing:-2px}.area span{font-size:14px;letter-spacing:0;font-weight:400}.muted{font-size:12px;line-height:1.7;color:#788174}hr{border:0;border-top:1px solid #dce2d7;margin:22px 0}.row{display:flex;justify-content:space-between;font-size:13px;margin:16px 0}.row small{color:#7f887b}label{display:block;font-size:12px;margin:12px 0}input{accent-color:#355a43}aside p{font-size:12px;line-height:1.75}.note{background:#eeeadd;padding:14px;border-radius:8px;color:#776a50;font-size:12px;line-height:1.75}dialog{border:1px solid #ccd4c9;border-radius:10px;width:min(1100px,94vw);max-height:94vh;padding:18px}dialog::backdrop{background:#18362799}dialog svg{width:100%;height:auto}dialog button{position:sticky;top:0;float:right}@media(max-width:800px){header{padding:20px}.badge{display:none}main{grid-template-columns:1fr;height:auto}section{height:70vh;min-height:500px}aside{border-left:0}h1{font-size:23px}}
</style></head><body><header><div><div class="kicker">OFFICE / SPACE STUDY 01</div><h1>30평 사무실 · 공간 배치 A안</h1><p>직원 8석 + 대표실 · 6인 회의실 · 탕비실</p></div><span class="badge">가정 치수 · 업체 상담용</span></header><main><section><canvas id="view"></canvas><div class="tools"><button id="reset">3D 기본 시점</button><button id="top">위에서 보기</button><button id="plan">치수 평면도</button><button id="save">화면 저장</button></div><div class="hint">드래그 회전 · 휠 확대 · 우클릭 드래그 이동</div></section><aside><h2>공간 개요</h2><div class="area">99 <span>㎡ / 약 29.95평</span></div><p class="muted">실내 외곽 11,000 × 9,000 mm<br>천장 높이 2,700 mm 가정</p><hr><div class="row"><b>01 대표실</b><small>11.06㎡</small></div><div class="row"><b>02 회의실</b><small>14.07㎡ · 6석</small></div><div class="row"><b>03 탕비실</b><small>11.06㎡</small></div><div class="row"><b>04 업무 공간</b><small>직원 8석</small></div><p class="muted">실 면적은 칸막이 안쪽 기준.<br>잔여 면적은 업무·입구·통로·칸막이.</p><hr><label><input id="walls" type="checkbox"> 외벽 전체 높이 보기</label><label><input id="labels" type="checkbox" checked> 공간 이름 표시</label><p class="muted">기본 화면은 내부가 보이도록 외벽을 낮게 표시합니다.</p><hr><div class="note">현장 실측 전 개념안입니다. 출입문·창문·기둥 유무·급배수 위치를 가정했습니다. 실제 시공 치수와 전기·설비는 업체 실측 후 확정하세요.</div></aside></main><dialog id="planModal"><button id="closePlan">닫기</button>SVG</dialog><script>window.LAYOUT=DATA;</script><script>BUNDLE</script></body></html>'''
page=page.replace('SVG',svg).replace('DATA',data).replace('BUNDLE',bundle)
(out/'00_사무실_3D.html').write_text(page)
