# -*- coding: utf-8 -*-
from pathlib import Path
import base64
r=Path(__file__).resolve().parent.parent/'output'
svg=(r/'01_치수평면도.svg').read_text()
pic=base64.b64encode((r/'3D_배치도.png').read_bytes()).decode()
css='''@page{size:A3 landscape;margin:0}*{box-sizing:border-box}body{margin:0;color:#294035;font-family:"Apple SD Gothic Neo",sans-serif}.page{width:420mm;height:297mm;padding:15mm 16mm 12mm;page-break-after:always;position:relative}.page:last-child{page-break-after:auto}header{height:29mm;display:flex;align-items:start;justify-content:space-between;border-bottom:1px solid #a6b6a6}.eyebrow{font-size:9px;letter-spacing:3px;color:#81917f}h1{font-size:25px;margin:5px 0 0;font-weight:650}header p{text-align:right;font-size:11px;line-height:1.65;margin:0;color:#6c796b}.body{display:grid;grid-template-columns:275mm 103mm;gap:10mm;padding-top:6mm}.plan svg{width:275mm;height:226mm}.side{padding-top:6mm}h2{font-size:15px;margin:0 0 12px}h3{font-size:12px;margin:19px 0 6px}p,li{font-size:11px;line-height:1.75}p{margin:5px 0 11px}ul,ol{padding-left:18px;margin:5px 0}.stat{background:#eef1e8;padding:15px;margin-bottom:18px}.stat b{font-size:28px}.stat span{font-size:12px}table{width:100%;border-collapse:collapse;font-size:10px}td,th{text-align:left;padding:8px 4px;border-bottom:1px solid #d6dfd0}.note{background:#f4efdf;padding:12px;font-size:10px;line-height:1.7;margin-top:17px}.foot{position:absolute;bottom:9mm;left:16mm;right:16mm;border-top:1px solid #c9d2c1;padding-top:3mm;display:flex;justify-content:space-between;font-size:9px;color:#798572}.render{width:275mm;border-radius:3mm;margin-top:4mm}.palette{display:flex;gap:14px;margin:12px 0;font-size:11px}.swatch{display:inline-block;width:12px;height:12px;margin-right:6px;vertical-align:middle}.caption{padding:10px 0;color:#6c7b68;font-size:10px}.sub{color:#788574}'''
page1='''<div class="page"><header><div><div class="eyebrow">OFFICE / SPACE STUDY 01</div><h1>30평 사무실 · 치수 평면도</h1></div><p>A안 · 직원 8석 + 대표 1석<br>2026.09.29 / 가정 치수 · 실측 전</p></header><div class="body"><div class="plan">SVG</div><div class="side"><div class="stat"><b>99㎡</b> <span>약 29.95평</span><p>실내 외곽 유효치수 가정<br>11,000 × 9,000 mm<br>천장 높이 2,700 mm</p></div><h2>공간 구성</h2><table><tr><th>구역</th><th>순치수 mm</th><th>면적</th></tr><tr><td>대표실</td><td>3,300 × 3,350</td><td>11.06㎡</td></tr><tr><td>회의실</td><td>4,200 × 3,350</td><td>14.07㎡</td></tr><tr><td>탕비실</td><td>3,300 × 3,350</td><td>11.06㎡</td></tr></table><p class="sub">나머지 면적: 업무·입구·통로·칸막이.<br>신설 칸막이 두께 100 mm 가정.</p><h3>가구와 동선</h3><ul><li>직원 책상 1,400 × 700 mm × 8개</li><li>대표 책상 1,800 × 800 mm × 1개</li><li>회의 테이블 2,400 × 1,050 mm / 6석</li><li>가로 공용 통로 약 1,200 mm 계획</li><li>각 실 개구부 900 / 현관 1,200 mm 가정</li></ul><h3>도면 읽기</h3><p>청록색 선: 유리·창호<br>연녹색 띠: 공용 통로<br>출입부 점선: 슬라이딩 도어 개념<br>실제 방위는 미지정</p><div class="note">치수 단위 mm · 축척 미지정<br>그림을 자로 재지 말고 표기 치수를 참고하세요. 현장 확인 후 시공용 도면으로 확정해야 합니다.</div></div></div><div class="foot"><span>가정 치수 / 공간 배치·견적 상담용 / 현장 시공 확정 도면 아님</span><span>A-01 · FLOOR PLAN</span></div></div>'''
page2='''<div class="page"><header><div><div class="eyebrow">OFFICE / SPACE STUDY 01</div><h1>공간을 한눈에 보는 3D 배치</h1></div><p>동일 좌표 기반 평면·3D 모델<br>2026.09.29 / 마감 방향 제안</p></header><div class="body"><div><img class="render" src="data:image/png;base64,PIC"><div class="caption">외곽벽을 낮게 잘라 내부를 보여주는 개념 모형. 각 실 높이는 2,700 mm 가정이며 도어 패널은 생략했습니다.</div><div class="palette"><span><i class="swatch" style="background:#eeeae2"></i>웜 화이트</span><span><i class="swatch" style="background:#c7a477"></i>내추럴 오크</span><span><i class="swatch" style="background:#819385"></i>세이지 그린</span><span><i class="swatch" style="background:#b0d3d8"></i>유리 칸막이</span></div><p>입구 → 직원 업무 공간 → 공용 통로 → 대표실·회의실·탕비실로 이어지는 구성입니다.<br>직원 4인 대면 배치를 두 그룹으로 나누고, 대표실은 별도 좌석을 둡니다.</p></div><div class="side"><h2>가정한 현장 조건</h2><ul><li>전용 약 30평, 직사각형 실내</li><li>내부 기둥·코어 없음</li><li>화장실은 사무실 외 공용부</li><li>아래쪽 오른편 출입구 1곳</li><li>후면 창호 3곳, 위치·크기 가정</li><li>탕비실 급배수 연결 가능 여부 미확인</li></ul><h3>시공업체 확인 후 확정</h3><ol><li>실측 외곽 치수와 기둥·창문·기존 출입구를 반영해 배치 조정.</li><li>급배수·전기·통신·냉난방·환기 위치 및 공사 가능 범위 확인.</li><li>유리 사양·회의실 차음·도어 방식·유효폭·의자 사용 동선 협의.</li><li>소방·피난·건물 관리 기준 검토 후 필요한 상세도 작성.</li></ol><h3>함께 전달하는 파일</h3><p>인터랙티브 3D HTML<br>확대 가능한 SVG 평면도<br>공유용 PNG 이미지<br>미터 단위 GLB 3D 모델<br>가정 조건과 확인 항목 메모</p><div class="note">이 안은 배치와 디자인 방향을 협의하기 위한 자료입니다. 시공 치수·설비 위치·공사비는 현장 실측과 상세 설계 후 확정하세요.</div></div></div><div class="foot"><span>3D와 평면은 같은 배치 데이터를 사용 · 구조·설비 상세 미포함</span><span>A-02 · 3D & DESIGN ASSUMPTIONS</span></div></div>'''
(r/'업체전달용_인쇄.html').write_text('<!doctype html><html lang="ko"><meta charset="utf-8"><title>30평 사무실 배치 검토안</title><style>'+css+'</style><body>'+page1.replace('SVG',svg)+page2.replace('PIC',pic)+'</body></html>')
